-- Tłumaczenia drinków (EN) → drink_translations (name + remarks)
-- Uruchom w Supabase SQL Editor. Idempotentne.

insert into drink_translations (drink_id, lang, name, note, remarks) values ('bluepinacolada', 'en', 'Blue Piña Colada', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('czasapokalipsy', 'en', 'Apocalypse Now', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('darknstormy', 'en', 'Dark ''n'' Stormy', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('dzidzi', 'en', 'Dzidzi', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('ginfizz', 'en', 'Gin Fizz', NULL, 'Serve without ice.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('gromwraju', 'en', 'Thunder in Paradise', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('johncollins', 'en', 'John Collins', NULL, 'For a Tom Collins, use Old Tom gin.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('johnybravo', 'en', 'Johnny Bravo', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lemoniadaarbuzowa', 'en', 'Watermelon Lemonade', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lemoniadacytrynowa', 'en', 'Lemon Lemonade', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lemoniadamalinowa', 'en', 'Raspberry Lemonade', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lemoniadatruskawkowa', 'en', 'Strawberry Lemonade', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lemoniadazmieta', 'en', 'Mint Lemonade', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('lowcaandroidow', 'en', 'Blade Runner', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('maitai', 'en', 'Mai Tai', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('margaritatruskawkowa', 'en', 'Strawberry Margarita', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('marktwaincoctail', 'en', 'Mark Twain Cocktail', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('mimosa', 'en', 'Mimosa', NULL, 'Also known as a Buck''s Fizz.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('mojitozogorkiemiimbirem', 'en', 'Cucumber & Ginger Mojito', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('mrocznyrycerz', 'en', 'The Dark Knight', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('pigwowekamikaze', 'en', 'Quince Kamikaze', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('pinacolada', 'en', 'Piña Colada', NULL, 'Traditionally a few drops of fresh lime juice were added for flavour. Instead of the juice you can use 4 slices of fresh pineapple.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('planterspunch', 'en', 'Planter''s Punch', NULL, 'Add water, ice or fresh juice to dilute the flavour.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('slonecznypatrol', 'en', 'Baywatch', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('southside', 'en', 'Southside', NULL, 'If using egg white, shake vigorously.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('spritz', 'en', 'Spritz', NULL, 'There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('terazpolska', 'en', 'Poland Now', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('upiorwoperze', 'en', 'The Phantom of the Opera', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('vento', 'en', 'VE.N.TO', NULL, 'If you like, the water can be replaced with a chamomile infusion mixed with honey.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('vieuxcarre', 'en', 'Vieux Carré', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('whiskeysour', 'en', 'Whiskey Sour', NULL, 'If using egg white, shake harder to release and integrate the foam from the white.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('wscieklypies', 'en', 'Mad Dog', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('zabojczabron', 'en', 'Lethal Weapon', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('zabojczynumer', 'en', 'Deadly Number', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('zartropikow', 'en', 'Tropical Heat', NULL, NULL) on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
insert into drink_translations (drink_id, lang, name, note, remarks) values ('zombie', 'en', 'Zombie', NULL, 'Donn''s Mix: 2 parts fresh yellow grapefruit and 1 part cinnamon syrup.') on conflict (drink_id, lang) do update set name = excluded.name, remarks = excluded.remarks;
